---
controller:
  config:
    compute-full-forwarded-for: "true"
    use-forwarded-headers: "true"
    proxy-body-size: "0"    
  ingressClass: external-nginx
  ingressClassResource:
    enabled: true
    default: false
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - ingress-nginx
        topologyKey: "kubernetes.io/hostname"
  replicaCount: 1
  admissionWebhooks:
    enabled: true
  service:
    annotations:
      # defaults to clasic
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      # to create internal load balancer with private ip
      # service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        lesson: "082"
